# Generated by Django 4.2 on 2023-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="capacity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="age",
            field=models.IntegerField(default=24),
        ),
    ]
