# Generated by Django 4.2 on 2023-05-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_group_capacity_alter_teacher_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.CharField(max_length=255),
        ),
    ]
