# Generated by Django 4.2 on 2023-05-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_alter_group_name_alter_teacher_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("year", models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name="group",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subjects",
        ),
    ]
