# Generated by Django 4.2 on 2023-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_student_remove_group_capacity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRemove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("year", models.IntegerField(default=1)),
            ],
        ),
    ]
