# Generated by Django 4.2 on 2023-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_delete_studentremove"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="delete",
            field=models.IntegerField(default=0),
        ),
    ]
